### ISSUE TITLE
Garbled ScreenPad Plus screen

### ISSUE THREAD

**Issue by thaiiy** [shiecldk/ASUS-ZenBook-Pro-Duo-15-OLED-UX582-Hackintosh#2] opened 2021-11-17 14:16 UTC
Hi there, thanks for this repo!
I have the ZenBook Duo UX481 so it's fairly simlar. It booted without issues with your EFI straight away.

However, secondary screen is not working, garbled as in the picture attached. Any ideas? Thanks 

![20211118_011100](https://user-images.githubusercontent.com/89678317/142217147-8737a0cb-dc8e-422d-af7b-636c79521be2.jpg)

**Comment by shiecldk** [comment] 2021-11-18 02:28
Hi @thaiiy, have you followed this guide? https://www.tonymacx86.com/threads/guide-general-framebuffer-patching-guide-hdmi-black-screen-problem.269149/

What's the screenshot of the connector section in Hackintool.app on your UX481?

**Comment by shiecldk** [comment] 2021-11-24 01:13
@thaiiy Any update for your issue? If not, I will close this thread.

**Comment by thaiiy** [comment] 2021-11-25 13:32
Thanks for following up on this.

I have tried changing BusID etc, just the simple stuff but haven't been
successful. I tried turning output to the screen off using the RDM app but
that didn't work either.

I haven't and don't think I will get time to work this one out using your
link. So unless someone else wants to chime in, I won't have any further
updates.

**Comment by shiecldk** [comment] 2021-11-26 03:42
Hi, @thaiiy. Please send a screenshot of the connector section in Hackintool.app. No one cannot help without knowing the device setup (iGPU pin connection) on your laptop.

**Comment by shiecldk** [comment] 2021-11-29 15:52
Issue closed due to inactive from the original post.

**Comment by shiecldk** [comment] 2021-11-29 15:52
Issue closed due to inactive from the original post.

**Closed as completed by shiecldk** 2021-11-29 15:52 UTC

**Comment by Qonfused** [comment] 2022-06-15 08:13
Hi, @shiecldk. I have the same laptop (w/ i7 10510u) and also haven't had success using the framebuffer patching guide on Monterey.

<details><summary>Device Specs:</summary><p>

```ini
[ASUS Zenbook Duo 14" Laptop (UX481FL-XS74T)]
```
```md
|    [CPU][Intel Core i7-10510U 4-core Processor]
|        └──[iGPU][Intel UHD Graphics 620]
|   [Wifi][Intel Wi-Fi 6 AX201 (802.11ax), Bluetooth 5]
| [Memory][Micron 16GB (4x4GB) LPDDR3-2133 CL16]
|   [dGPU][Nvidia GeForce MX250 2GB (10W 1D52 version; disabled)]
|[Storage][Samsung 970 Evo 500GB M.2-2280 NVMe SSD]
|        ├──[Bootloader][OpenCore 0.7.3]
|        ├──[Operating System][MacOS Monterey 12.0 Beta 6]
|        └──[Operating System][Microsoft Windows 11 Pro 64-bit]
|  [Audio][Realtek HD Audio (ASUS SonicMaster)]
|[Battery][Dynapack 70Wh (15.4V; 4440mAh) 4-cell LiPo Battery]
```

</p></details>

This is what the connectors section of Hackintool looks like for me:
![Screen Shot 2022-06-15 at 2 19 13 AM](https://user-images.githubusercontent.com/32466081/173768388-4ad538db-b6b2-46ee-9a43-89fd2f3311c8.png)

^^^ In red I believe is the second display (idx 1, port 5) and hdmi is on port 4 (idx 2); the primary display is still on port 0 (idx 0).

I've tried applying patches from hackintool after changing the display type for the screenpad to LVDS and changing the hdmi connector to the HDMI type. From the original config in this repo, I renamed connectors 1-3 to 0-2, and also removed the `enable-max-pixel-clock-override` key, but beyond that only the framebuffer connector properties were changed (removing all-data keys and adding pipe/type keys).

Additionally, I also changed the platform-id/device-id for integrated graphics to match the 10510u (UHD 620), but this also still shows up as UHD 630 in Hackintool (and 'Intel HD Graphics CFL CRB 2048 MB' in the about this mac window). This could be related but I'm not sure if this is still problematic for patching the iGPU or just cosmetic.

I've included my DeviceProperties section of my plist below before/after patching w/ the hackintool patches below:

<details><summary>Before patches</summary><p>

```
<key>DeviceProperties</key>
<dict>
	<key>Add</key>
	<dict>
		<key>PciRoot(0x0)/Pci(0x1F,0x0)</key>
		<dict>
			<key></key>
			<data></data>
			<key>AAPL,slot-name</key>
			<string>Internal@0,31,0</string>
			<key>device_type</key>
			<string>Low Pin Count (LPC) Bus</string>
			<key>model</key>
			<string>Comet Lake LPC Bus</string>
		</dict>
		<key>PciRoot(0x0)/Pci(0x1F,0x3)</key>
		<dict>
			<key>AAPL,slot-name</key>
			<string>Internal@0,31,3</string>
			<key>device_type</key>
			<string>Audio device</string>
			<key>hda-gfx</key>
			<string>onboard-1</string>
			<key>layout-id</key>
			<data>FQAAAA==</data>
			<key>model</key>
			<string>Comet Lake PCH cAVS</string>
		</dict>
		<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
		<dict>
			<key>AAPL,ig-platform-id</key>
			<data>AACbPg==</data>
			<key>device-id</key>
			<data>mz4AAA==</data>
			<key>AAPL,slot-name</key>
			<string>Internal@0,2,0</string>
			<key>device_type</key>
			<string>VGA compatible controller</string>
			<key>dpcd-max-link-rate</key>
			<data>FAAAAA==</data>
			<key>enable-dpcd-max-link-rate-fix</key>
			<data>AQAAAA==</data>
			<key>enable-hdmi20</key>
			<data>AQAAAA==</data>
			<key>enable-lspcon-support</key>
			<data>AQAAAA==</data>
			<key>enable-max-pixel-clock-override</key>
			<data>AQAAAA==</data>
			<key>framebuffer-con1-alldata</key>
			<data>AQUJAAAEAACHAQAA</data>
			<key>framebuffer-con1-enable</key>
			<data>AQAAAA==</data>
			<key>framebuffer-con2-alldata</key>
			<data>AgYJAAAEAACHAQAA</data>
			<key>framebuffer-con2-enable</key>
			<data>AQAAAA==</data>
			<key>framebuffer-con3-alldata</key>
			<data>AwQKAAAIAACHAQAA</data>
			<key>framebuffer-con3-enable</key>
			<data>AQAAAA==</data>
			<key>framebuffer-con3-has-lspcon</key>
			<data>AQAAAA==</data>
			<key>framebuffer-patch-enable</key>
			<data>AQAAAA==</data>
			<key>framebuffer-portcount</key>
			<data>BAAAAA==</data>
			<key>framebuffer-unifiedmem</key>
			<data>AAD//w==</data>
			<key>hda-gfx</key>
			<string>onboard-1</string>
		</dict>
	</dict>
	<key>Delete</key>
	<dict/>
</dict>
```

</p></details>

<details><summary>With patches</summary><p>

```
<key>DeviceProperties</key>
<dict>
	<key>Add</key>
	<dict>
		<key>PciRoot(0x0)/Pci(0x1F,0x0)</key>
		<dict>
			<key></key>
			<data></data>
			<key>AAPL,slot-name</key>
			<string>Internal@0,31,0</string>
			<key>device_type</key>
			<string>Low Pin Count (LPC) Bus</string>
			<key>model</key>
			<string>Comet Lake LPC Bus</string>
		</dict>
		<key>PciRoot(0x0)/Pci(0x1F,0x3)</key>
		<dict>
			<key>AAPL,slot-name</key>
			<string>Internal@0,31,3</string>
			<key>device_type</key>
			<string>Audio device</string>
			<key>hda-gfx</key>
			<string>onboard-1</string>
			<key>layout-id</key>
			<data>FQAAAA==</data>
			<key>model</key>
			<string>Comet Lake PCH cAVS</string>
		</dict>
		<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
		<dict>
			<key>AAPL,ig-platform-id</key>
			<data>AACbPg==</data>
			<key>AAPL,slot-name</key>
			<string>Internal@0,2,0</string>
			<key>device-id</key>
			<data>mz4AAA==</data>
			<key>device_type</key>
			<string>VGA compatible controller</string>
			<key>dpcd-max-link-rate</key>
			<data>FAAAAA==</data>
			<key>enable-dpcd-max-link-rate-fix</key>
			<data>AQAAAA==</data>
			<key>framebuffer-con0-enable</key>
			<data>AQAAAA==</data>
			<key>framebuffer-con0-pipe</key>
			<data>EgAAAA==</data>
			<key>framebuffer-con1-enable</key>
			<data>AQAAAA==</data>
			<key>framebuffer-con1-pipe</key>
			<data>EgAAAA==</data>
			<key>framebuffer-con1-type</key>
			<data>AgAAAA==</data>
			<key>framebuffer-con2-enable</key>
			<data>AQAAAA==</data>
			<key>framebuffer-con2-has-lspcon</key>
			<data>AQAAAA==</data>
			<key>framebuffer-con2-pipe</key>
			<data>EgAAAA==</data>
			<key>framebuffer-con2-type</key>
			<data>AAgAAA==</data>
			<key>framebuffer-patch-enable</key>
			<data>AQAAAA==</data>
			<key>framebuffer-unifiedmem</key>
			<data>AAAAgA==</data>
			<key>hda-gfx</key>
			<string>onboard-1</string>
		</dict>
	</dict>
	<key>Delete</key>
	<dict/>
</dict>
```

</p></details>

<details><summary>Hackintool patch</summary><p>

```
<key>DeviceProperties</key>
<dict>
	<key>Add</key>
	<dict>
		<key>PciRoot(0x0)/Pci(0x1F,0x3)</key>
		<dict>
			<key>AAPL,slot-name</key>
			<string>Internal@0,31,3</string>
			<key>device_type</key>
			<string>Audio device</string>
			<key>hda-gfx</key>
			<string>onboard-1</string>
			<key>layout-id</key>
			<data>
			FQAAAA==
			</data>
			<key>model</key>
			<string>Comet Lake PCH-LP cAVS</string>
		</dict>
		<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
		<dict>
			<key>AAPL,ig-platform-id</key>
			<data>
			CQClPg==
			</data>
			<key>AAPL,slot-name</key>
			<string>Internal@0,2,0</string>
			<key>device-id</key>
			<data>
			mz4AAA==
			</data>
			<key>device_type</key>
			<string>VGA compatible controller</string>
			<key>enable-hdmi20</key>
			<data>
			AQAAAA==
			</data>
			<key>framebuffer-con0-enable</key>
			<data>
			AQAAAA==
			</data>
			<key>framebuffer-con0-pipe</key>
			<data>
			EgAAAA==
			</data>
			<key>framebuffer-con1-enable</key>
			<data>
			AQAAAA==
			</data>
			<key>framebuffer-con1-pipe</key>
			<data>
			EgAAAA==
			</data>
			<key>framebuffer-con1-type</key>
			<data>
			AgAAAA==
			</data>
			<key>framebuffer-con2-enable</key>
			<data>
			AQAAAA==
			</data>
			<key>framebuffer-con2-pipe</key>
			<data>
			EgAAAA==
			</data>
			<key>framebuffer-con2-type</key>
			<data>
			AAgAAA==
			</data>
			<key>framebuffer-patch-enable</key>
			<data>
			AQAAAA==
			</data>
			<key>framebuffer-unifiedmem</key>
			<data>
			AAAAgA==
			</data>
			<key>hda-gfx</key>
			<string>onboard-1</string>
			<key>model</key>
			<string>Intel CoffeeLake-H GT2 [UHD Graphics 630]</string>
		</dict>
	</dict>
</dict>
```

</p></details>

**Comment by Qonfused** [comment] 2022-06-17 06:11
I think I see what I'm doing wrong lol. I'll work on a fix w/ touchscreen and probably make a new issue with other misc fixes for this specific model (if you want that here).

**Comment by danperks** [comment] 2022-07-11 16:05
@Qonfused I have exactly the same issue, did you ever come up with a fix? For context, I just found this thread so haven't even downloaded Hackintool to see if I can fix it there.

**Comment by Maleficent-Magik** [comment] 2022-08-01 20:26
I reopen the debate! Has there been any advancement? @danperks @Qonfused

**Comment by danperks** [comment] 2022-08-01 20:34
Glad another has joined the quest, I have found nothing as of yet. Honestly considering paying someone on the r/Hackintosh Reddit/Discord to tell me how to fix it lol!

**Comment by Qonfused** [comment] 2022-08-01 21:31
Sorry I meant to create a gist to dump everything in (w/ removing or changing some pro-duo specific kexts and SSDTs, etc). I got busy with work and with Metal 3 w/ Ventura on my main machine since then so I don’t think I got much done for the non-pro zenbook duo.
I’m at vacation atm but I’ll get some free time to work on this again come Thursday.

**Comment by danperks** [comment] 2022-08-01 21:37
Anything you may have to help would be great. I do have the Pro Duo so any help you have that may be of use for my device would be fantastic. 

Once time is more on my side, I am hoping to learn more about this kind of stuff!

**Comment by Maleficent-Magik** [comment] 2022-08-02 12:28
Personally, I had managed at one point not to have the screen blurred, but how? I don't know anymore hahaha ...! but since then, it came back blurry heh

Concerning @Qonfused 's vacations, well, happy vacations to you ! There is no worry about the timing, for now I stay on Windows x) but MacOS would be a plus for some things.
Unfortunately, I don't know if @danperks tried to boot on Monterey but personally, I didn't succeed x) I crash on ACPI

On that note, good work to all of you and hope to get something done haha, have a good day to both of you!

See you soon!

**Comment by Qonfused** [comment] 2022-08-06 04:35
I wanted to leave a quick update since I forgot to leave one the other day.

I couldn't find my monterey drive from June but from what I recall both displays would work separately but not at the same time (black screen for the other display; seems to be the same issue shiecldk ran into [here](https://www.insanelymac.com/forum/topic/334899-intel-framebuffer-patching-using-whatevergreen/?do=findComment&comment=2764047)).

<details><summary>Also for reference, this is the configuration of the laptop I'm using for testing:</summary>

|Component | Brand |
|--- | --- |
|CPU | Intel Core i7-10510U (Comet Lake) 4-core Processor [^0a]|
|iGPU | Intel UHD Graphics 620|
|dGPU | Nvidia GeForce MX250 2GB (10W 1D52 version; disabled)|
|Audio | Realtek ALC???|
|Memory | 16GB LPDDR3 2133MHz Cl16 (4x4 GB Micron Modules)|
|Wifi & Bluetooth | • Intel AX201 WiFi 6<br>• Bluetooth 5.0|
|Storage | Intel 660p 1TB M.2-2280 NVMe SSD|
|Camera | Windows Hello HD Camera with IR|
|Trackpad | ELAN????, ?|
|Display | • 14" (1920 x 1080) IPS display<br>• 12.6" (1920 x 515) IPS Screenpad Plus display|
|Touch Screen | • ELAN????, \\_SB.PCI0.I2C?.????, ?<br>• ELAN????, \\_SB.PCI0.I2C?.????, ?| |Ports | (Left)<br>• 1x 4.5mm DC-in (19V; 3.42A)<br>• 1x HDMI 1.4<br>• 1x USB 3.1 Gen 2 Type-A<br>• 1x USB 3.1 Gen 2 Type-C<br>(Right)<br>• 1x USB 3.1 Gen 1 Type-A<br>• 1x 3.5 mm Audio combo jack<br>• 1x MicroSD card reader<br>|
|Battery | Dynapack 70Wh (15.4V; 4440mAh) 4-cell LiPo Battery|
[^0a]: [Intel Core i7-10510U - Intel Ark Page](https://ark.intel.com/content/www/us/en/ark/products/196449/intel-core-i710510u-processor-8m-cache-up-to-4-90-ghz.html)

^ I need to fill in some missing info for the trackpad/touchscreen since I've lost the original drive (I think the non-pro zenbook duo uses the same Realtek ALC294 as the pro-duo though).
</details>

I've spent pretty much all of yesterday and today figuring out how OpenCore overrides the `AppleIntelCFLGraphicsFramebuffer` kext used for both the UHD 620 and UHD 630 iGPUs (since I still had no idea what was actually happening with framebuffer/connector patches). I'm hoping to figure this out the next couple of days since this mainly only tedious to go through all the framebuffer/platform ids.

---

Concerning my previous post, this is the previous framebuffer data that I used before for framebuffer id `3EA50009` (from the [WhateverGreen Manual](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md#intel-uhd-graphics-610-655-coffee-lake-and-comet-lake-processors)):

Index | Name | Connector Type | Port Number | Pipe | Flags
--- | --- | --- | --- | --- | ---
0 | Framebuffer0 | `LVDS and eDP` | `0x0` | `8` | `98000000`
1 | Framebuffer1 | `Displayport` | `0x5` | `9` | `C7010000`
2 | Framebuffer2 | `Displayport` | `0x4` | `A` | `C7010000`

^ This apparently is actually the same framebuffer-id used in this repo for the i9-10980HK/Intel Core i7-10870H (which both have UHD 630 iGPUs). I before noted Framebuffer0 and Framebuffer1 showed displays attached in macOS with this framebuffer-id in my previous post, but no connector patch worked (maybe because I wasn't using the correct framebuffer-id for the iGPU?).

<details><summary>For reference, the connector patches for the pro-duo (UX582 w/ UHD 630 iGPU) are mapped very similarly to what I'd expect:</summary>

Key | Type | Value
--- | --- | ---
AAPL,ig-platform-id | Data | `0900A53E`
framebuffer-con1-enable | Data | `01000000`
framebuffer-con1-alldata | Data |  `01050900 00040000 87010000`
framebuffer-con2-enable | Data | `01000000`
framebuffer-con2-alldata | Data | `02060900 00040000 87010000`
framebuffer-con3-enable | Data | `01000000`
framebuffer-con3-alldata | Data | `03040A00 00080000 87010000`
framebuffer-patch-enable | Data | `01000000`
framebuffer-portcount | Data | `04000000`
framebuffer-unifiedmem | Data | `0000FFFF`

</details>

^ To me these would appear to have the wrong flags for the `3EA50009` framebuffer id used here (the flag would supposed to be `C7010000`) but not for the `3E9B0000` framebuffer id (the flag here would be `87010000`). This is mostly what was throwing me off trying to test various bus-ids, etc for patching the screenpad-plus (and for finding the right framebuffer-id since these patches are the only indication of whether the screenpad plus is both mapped correctly and is using the right connector + busid).

^^ The other main thing to note is that the screenpad-plus for the pro-duo is connected to port 1 and busID 5 (the first part of the alldata patch; `01050900` --> `01` port, `05` busID, `0900` pipe), and both the primary display and secondary display are mapped as displayport (the second part of the alldata patch; `00040000`). These I thought would both be mapped as LVDS/eDP since they're internal displays (and the connector type for the screenpad plus is eDP)?

The first framebuffer from the table (framebuffer0) seems to be unused for that configuration? I think before I assumed framebuffer0 to be the primary display but was confused when modifying the busID for the second framebuffer (framebuffer1) since I recall it would cause a black screen for the primary display since I was instead dealing with the primary display, not the screenpad plus.

---

I've been starting from here to find the proper framebuffer-id before doing any connector patching:

![image](https://user-images.githubusercontent.com/32466081/183229215-d895cdb8-b29b-4268-8d62-08719f623d63.png)

^ Above should work for both the i5-10210u and i7-10510u, which for this framebuffer-id has these properties:
Index | Name | Connector Type | Port Number | Pipe | Flags
--- | --- | --- | --- | --- | ---
0 | Framebuffer0 | `LVDS and eDP` | `0x0` | `8` | `98000000`
1 | Framebuffer1 | `Displayport` | `0x5` | `9` | `87010000`
2 | Framebuffer2 | `Displayport` | `0x4` | `A` | `87010000`

This is the list of framebuffer ids from the CFL/CML section of the whatevergreen manual that I need to go through (I've converted the ids from small endian to big endian for OpenCore):
Framebuffer ID | (AAPL,ig-platform-id) | Type | Connectors | Stolen Memory | Tested
--- | --- | --- | --- | --- | :-:
`0x3EA50009` | `0900A53E` | mobile | 3 | 58 MB | yes
`0x3E920009` | `0900923E` | mobile | 3 | 58 MB | ?
`0x3E9B0009` | `09009B3E` | mobile | 3 | 58 MB | ?
`0x3EA50000` | `0000A53E` | mobile | 3 | 58 MB | ?
`0x3E920000` | `0000923E` | mobile | 3 | 58 MB | ?
`0x3E000000` | `0000003E` | mobile | 3 | 58 MB | ?
`0x3E9B0000` | `00009B3E` <-- Default | mobile | 3 | 58 MB | yes
`0x3EA50004` | `0400A53E` | mobile | 3 | 58 MB | ?
`0x3EA50005` | `0500A53E` | mobile | 3 | 58 MB | ?
`0x3EA60005` | `0500A63E` | mobile | 3 | 58 MB | ?

I'll also ask in the Hackintosh Discord how I should be testing these framebuffer-ids since I'd otherwise be enumerating every bus-id and connector index from the [dortania guide](https://dortania.github.io/OpenCore-Post-Install/gpu-patching/intel-patching/busid.html#mapping-the-video-ports) (and/or from the other guide mentioned before on [tonymacx64](https://www.tonymacx86.com/threads/guide-general-framebuffer-patching-guide-hdmi-black-screen-problem.269149/#Procedure)) to test that the primary display is working, and that the secondary screenpad-plus display is properly recognized in display settings (and hopefully eventually working w/ the primary display).

Let me know if anything here doesn't seem correct since I'm not 100% sure on this (this is still my first time dealing with a laptop hackintosh w/ framebuffer patches, etc).

**Comment by Qonfused** [comment] 2022-08-06 05:48
> Personally, I had managed at one point not to have the screen blurred, but how? I don't know anymore hahaha ...! but since then, it came back blurry heh
> 
> Concerning @Qonfused 's vacations, well, happy vacations to you ! There is no worry about the timing, for now I stay on Windows x) but MacOS would be a plus for some things. Unfortunately, I don't know if @danperks tried to boot on Monterey but personally, I didn't succeed x) I crash on ACPI
> 
> On that note, good work to all of you and hope to get something done haha, have a good day to both of you!
> 
> See you soon!

@UsedDiscord I'd try a Monterey version after Beta 12.3 to be sure (I'm testing on 12.4 public build 21F79), but there were some ACPI patches I had to modify that otherwise might have caused that issue? I've created a fork [here](https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh) with what I'm currently using but please remember to use GenSMBIOS to generate your own serial & board data before trying to setup iCloud! I've included a warning in the README linking to instructions for that.

I'd also use this or suggest changes to this to verify that any framebuffer patches I find work on my machine also work on yours (if you have a different hardware configuration, etc).

**Comment by Maleficent-Magik** [comment] 2022-08-06 17:03
> > Personally, I had managed at one point not to have the screen blurred, but how? I don't know anymore hahaha ...! but since then, it came back blurry heh
> > Concerning @Qonfused 's vacations, well, happy vacations to you ! There is no worry about the timing, for now I stay on Windows x) but MacOS would be a plus for some things. Unfortunately, I don't know if @danperks tried to boot on Monterey but personally, I didn't succeed x) I crash on ACPI
> > On that note, good work to all of you and hope to get something done haha, have a good day to both of you!
> > See you soon!
> 
> @UsedDiscord I'd try a Monterey version after Beta 12.3 to be sure (I'm testing on 12.4 public build 21F79), but there were some ACPI patches I had to modify that otherwise might have caused that issue? I've created a fork [here](https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh) with what I'm currently using but please remember to use GenSMBIOS to generate your own serial & board data before trying to setup iCloud! I've included a warning in the README linking to instructions for that.
> 
> I'd also use this or suggest changes to this to verify that any framebuffer patches I find work on my machine also work on yours (if you have a different hardware configuration, etc).
------------------------------------------

Hello ! Glad to see you in my inbox early in the morning! I hope you are doing well.
Well, I'm starting a bit backwards for your reading x)...

Concerning MacOS Monterey, I thank you very much! but really very much! 
I was able to take your EFI that you posted (linked to your Fork) and put it on my usb key, good news, everything starts (OpenCore + OpenCore GUI (Thank you! it is also sublime) )! 
When I went on the Recovery of MacOS Monterey; it was able to find my wifi password already registered on MacOS BigSur (I had already installed BigSur because as I said : )
> I crash on ACPI µ

so now no problem. 

The installation went well, he found my NVMe disk on the first try (Normal, he already had MacOS BigSur)

Strangely, it didn't get stuck where it is supposed to be stuck... I always screw up my installations, I get stuck at the "Less than a minute left" moment... strangely, it restarted by itself! and it was able to finish its installation properly.

So once I was able to boot on MacOS Monterey, everything was fine! The keyboard is now backlit! (Big & huge thanks) the USB works properly (unlike before where the key ejected itself)! and the sound, wow! it works perfectly! there is no lag. BT & Wifi works! (Airdrop would be available (not tested) ). 

So already, a huge thank you for your work that I could not reproduce ...

Now, what is blocking : 
-> The trackpad doesn't work but the keyboard itself does (except the F1,F2 ect ect keys (maybe pressed FN+Fx?)). 

-> The second screen (aka: ScreenPad) always decides to make the face, and to blur, well, in the meantime, I did not modify your configuration, except the SMBIOS that I modified as requested of course. I will try a little, but it's long to always restart the computer... we lose a crazy time x). 

What I haven't tested yet: 

-> Sleep, AirDrop, 
-> the camera, 
-> Touch screen (on the scrambled Screenpad, it works..)

I could also see that during the startup, there are problems of "KEXT" so, it's quite strange, I'll look at the logs tonight ( at the time of writing, it's 7pm)
So already, a big thank you for all this! I'll read your first part and answer a bit! in the meantime, good evening! 

-- UsedDiscord

(EDIT : 7pm06 : (My PC is also a Comet Lake and a UHD 620 / GT2 / HD630, I don't really understand but hey...) so we can take the same configuration!)

**Comment by Maleficent-Magik** [comment] 2022-08-06 18:24
btw, which SMBios would you select?

**Comment by Qonfused** [comment] 2022-08-06 21:27
> btw, which SMBios would you select?

@UsedDiscord Use MacBookPro16,1. I meant regenerating your board no. and serial number btw with that earlier message. It's to prevent issues with people setting up different installs w/ the same serial info for iServices.

**Comment by Maleficent-Magik** [comment] 2022-08-06 21:37
> I meant regenerating your board no. and serial number btw with that earlier message. It's to prevent issues with people setting up different installs w/ the same serial info for iServices

Okay! I'll use GenSMBIOS with MacBookPro16,1. Thanks again to you!
Tomorrow I'll try the other framebuffer and get back to you.
For me, it's 11:37 pm, it's a good night ^^ for you, I wish you a good day or a good night !
